Networkteam:
  Neos:
    FrontendLogin:

      redirectOnLoginLogoutExceptionUri: '/'
      authenticationProviderName: 'Networkteam.Neos.FrontendLogin:Frontend'
      
      # When requesting a node with an authenticated account but not having the required ReadNodePrivelege, the request is redirected to the first accessible member area in site
      redirectToAccessibleMemberArea: false

      # Add a list of subtree tags for a nodeType by role. Max 36 charcater and lower case only, @see \Neos\ContentRepository\Core\Feature\SubtreeTagging\Dto\SubtreeTag
      # 
      # roleSubtree:
      #   'Some.Package.Key:SomeRoleName':
      #     nodeType: 'Some.Package.Key:MemberAreaRoot'
      #     subtreeTags: ['some-subtree-tag']
      roleSubtree: []
        
